-- Table DDL owns the first persistence constraints so SQLite can apply them
-- during table creation.
--
-- Required constraints:
-- - strategy_definitions.strategy_id is the primary key.
-- - signal_generator_definitions.generator_id is the primary key.
-- - strategy_evaluations.evaluation_id is the primary key.
-- - signal_logs.signal_id is the primary key.
-- - every persistence table restricts use_yn to 'Y' or 'N'.
-- - every persistence table requires reg_ymd, reg_dt, upd_dt, and use_yn.
