CREATE TABLE IF NOT EXISTS research_runs (
    research_run_id TEXT NOT NULL PRIMARY KEY,
    target_id TEXT NOT NULL,
    mode TEXT NOT NULL CHECK (mode IN ('backtest', 'dry_run')),
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    candle_limit INTEGER NOT NULL CHECK (candle_limit > 0),
    snapshot_id TEXT,
    indicator_set_id TEXT,
    strategy_result_id TEXT,
    generated_signal_id TEXT,
    evaluation_id TEXT,
    metadata TEXT,
    reg_ymd TEXT NOT NULL,
    reg_dt TEXT NOT NULL,
    upd_dt TEXT NOT NULL,
    use_yn TEXT NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    FOREIGN KEY (snapshot_id) REFERENCES market_snapshots (snapshot_id),
    FOREIGN KEY (indicator_set_id) REFERENCES indicator_sets (indicator_set_id),
    FOREIGN KEY (strategy_result_id) REFERENCES strategy_results (result_id),
    FOREIGN KEY (generated_signal_id) REFERENCES generated_signals (generated_signal_id),
    FOREIGN KEY (evaluation_id) REFERENCES strategy_evaluations (evaluation_id),
    CHECK (research_run_id <> ''),
    CHECK (target_id <> ''),
    CHECK (symbol <> ''),
    CHECK (timeframe <> '')
);
