CREATE TABLE IF NOT EXISTS trade_runs (
    trade_run_id TEXT NOT NULL PRIMARY KEY,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    candle_limit INTEGER NOT NULL CHECK (candle_limit > 0),
    snapshot_id TEXT,
    indicator_set_id TEXT,
    signal_id TEXT NOT NULL,
    generator_id TEXT NOT NULL,
    generated_signal_id TEXT,
    exposure_limit_id TEXT,
    risk_check_id TEXT,
    order_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('order_submitted', 'skipped', 'risk_rejected')),
    reason TEXT,
    payload TEXT,
    reg_ymd TEXT NOT NULL,
    reg_dt TEXT NOT NULL,
    upd_dt TEXT NOT NULL,
    use_yn TEXT NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    FOREIGN KEY (snapshot_id) REFERENCES market_snapshots (snapshot_id),
    FOREIGN KEY (indicator_set_id) REFERENCES indicator_sets (indicator_set_id),
    FOREIGN KEY (generated_signal_id) REFERENCES generated_signals (generated_signal_id),
    FOREIGN KEY (exposure_limit_id) REFERENCES exposure_limits (exposure_limit_id),
    FOREIGN KEY (risk_check_id) REFERENCES risk_checks (risk_check_id),
    FOREIGN KEY (order_id) REFERENCES order_results (order_id),
    CHECK (trade_run_id <> ''),
    CHECK (symbol <> ''),
    CHECK (timeframe <> ''),
    CHECK (signal_id <> ''),
    CHECK (generator_id <> '')
);
