CREATE TABLE IF NOT EXISTS candles (
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    opened_at TEXT NOT NULL,
    closed_at TEXT NOT NULL,
    open_price NUMERIC NOT NULL,
    high_price NUMERIC NOT NULL,
    low_price NUMERIC NOT NULL,
    close_price NUMERIC NOT NULL,
    volume NUMERIC NOT NULL CHECK (volume >= 0),
    source TEXT,
    payload TEXT,
    reg_ymd TEXT NOT NULL,
    reg_dt TEXT NOT NULL,
    upd_dt TEXT NOT NULL,
    use_yn TEXT NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    PRIMARY KEY (symbol, timeframe, opened_at),
    CHECK (symbol <> ''),
    CHECK (timeframe <> ''),
    CHECK (closed_at > opened_at),
    CHECK (low_price <= high_price),
    CHECK (open_price >= low_price AND open_price <= high_price),
    CHECK (close_price >= low_price AND close_price <= high_price)
);
