CREATE TABLE IF NOT EXISTS execution_reports (
    report_id TEXT NOT NULL PRIMARY KEY,
    request_id TEXT NOT NULL,
    order_id TEXT NOT NULL,
    position_id TEXT,
    symbol TEXT NOT NULL,
    client_order_id TEXT NOT NULL,
    exchange_order_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('accepted', 'rejected', 'filled', 'partially_filled', 'canceled')),
    executed_quantity NUMERIC,
    average_price NUMERIC,
    reduce_only INTEGER NOT NULL DEFAULT 0 CHECK (reduce_only IN (0, 1)),
    executed_dt TEXT NOT NULL,
    payload TEXT,
    reg_ymd TEXT NOT NULL,
    reg_dt TEXT NOT NULL,
    upd_dt TEXT NOT NULL,
    use_yn TEXT NOT NULL DEFAULT 'Y' CHECK (use_yn IN ('Y', 'N')),
    FOREIGN KEY (request_id) REFERENCES order_requests (request_id),
    FOREIGN KEY (order_id) REFERENCES order_results (order_id),
    FOREIGN KEY (position_id) REFERENCES positions (position_id),
    CHECK (report_id <> ''),
    CHECK (symbol <> ''),
    CHECK (client_order_id <> '')
);
