UPTREND = "UPTREND"
DOWNTREND = "DOWNTREND"
RANGE = "RANGE"
TRANSITION = "TRANSITION"
UNKNOWN = "UNKNOWN"

ALLOWED_REGIMES = {UPTREND, DOWNTREND, RANGE, TRANSITION, UNKNOWN}

REGIME_INTERVAL_1H = "1h"
REGIME_INTERVAL_15M = "15m"

MIN_1H_CANDLES = 200
MIN_15M_CANDLES = 400

REGIME_RANGE_ENTRY_ENV = "REGIME_RANGE_ENTRY_ENABLED"
REGIME_EMA_NEAR_PCT_ENV = "REGIME_EMA_NEAR_PCT"

DEFAULT_RANGE_ENTRY_ENABLED = False
DEFAULT_EMA_NEAR_PCT = 0.0015

INDICATOR_PARAMS_NAME = "regime_default"

BASELINE_WINDOW = 20
EMA_NEAR_LOOKBACK = 3
EMA_NEAR_CONTEXT_LOOKBACK = 6

TRANSITION_ATR_MULT = 1.8
TRANSITION_BB_MULT = 1.7

ADX_TREND_THRESHOLD = 25.0
ADX_RANGE_THRESHOLD = 20.0

TREND_ADX_BASE = 20.0
TREND_ADX_SCALE = 20.0
TREND_GAP_DENOM = 0.01

ATR_RISK_DENOM = 0.8
BB_RISK_DENOM = 0.7

EPSILON = 1e-8

HYSTERESIS_CONFIRM_COUNT = 2
